import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for InvoiceSettingQuoteSetting
void main() {
  final instance = InvoiceSettingQuoteSettingBuilder();
  // TODO add properties to the builder and call build()

  group(InvoiceSettingQuoteSetting, () {
    // Number of days within which a customer must pay invoices generated by this quote. This value will be `null` for quotes where `collection_method=charge_automatically`.
    // int daysUntilDue
    test('to test the property `daysUntilDue`', () async {
      // TODO
    });

    // ConnectAccountReference issuer
    test('to test the property `issuer`', () async {
      // TODO
    });

  });
}
