import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for InvoiceSettingSubscriptionSchedulePhaseSetting
void main() {
  final instance = InvoiceSettingSubscriptionSchedulePhaseSettingBuilder();
  // TODO add properties to the builder and call build()

  group(InvoiceSettingSubscriptionSchedulePhaseSetting, () {
    // The account tax IDs associated with this phase of the subscription schedule. Will be set on invoices generated by this phase of the subscription schedule.
    // BuiltList<InvoiceAccountTaxIdsInner> accountTaxIds
    test('to test the property `accountTaxIds`', () async {
      // TODO
    });

    // Number of days within which a customer must pay invoices generated by this subscription schedule. This value will be `null` for subscription schedules where `billing=charge_automatically`.
    // int daysUntilDue
    test('to test the property `daysUntilDue`', () async {
      // TODO
    });

    // ConnectAccountReference issuer
    test('to test the property `issuer`', () async {
      // TODO
    });

  });
}
