import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for MandatePaypal
void main() {
  final instance = MandatePaypalBuilder();
  // TODO add properties to the builder and call build()

  group(MandatePaypal, () {
    // The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
    // String billingAgreementId
    test('to test the property `billingAgreementId`', () async {
      // TODO
    });

    // PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
    // String payerId
    test('to test the property `payerId`', () async {
      // TODO
    });

  });
}
