//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

import 'package:openapi/api.dart';
import 'package:test/test.dart';

// tests for PaymentMethodDetailsPaypal
void main() {
  // final instance = PaymentMethodDetailsPaypal();

  group('test PaymentMethodDetailsPaypal', () {
    // Two-letter ISO code representing the buyer's country. Values are provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    // String country
    test('to test the property `country`', () async {
      // TODO
    });

    // Owner's email. Values are provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    // String payerEmail
    test('to test the property `payerEmail`', () async {
      // TODO
    });

    // PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
    // String payerId
    test('to test the property `payerId`', () async {
      // TODO
    });

    // Owner's full name. Values provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
    // String payerName
    test('to test the property `payerName`', () async {
      // TODO
    });

    // PaypalSellerProtection sellerProtection
    test('to test the property `sellerProtection`', () async {
      // TODO
    });

    // A unique ID generated by PayPal for this transaction.
    // String transactionId
    test('to test the property `transactionId`', () async {
      // TODO
    });


  });

}
