import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for PaymentMethodDetailsGrabpay
void main() {
  final instance = PaymentMethodDetailsGrabpayBuilder();
  // TODO add properties to the builder and call build()

  group(PaymentMethodDetailsGrabpay, () {
    // Unique transaction id generated by GrabPay
    // String transactionId
    test('to test the property `transactionId`', () async {
      // TODO
    });

  });
}
