import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for PaymentMethodDetailsPromptpay
void main() {
  final instance = PaymentMethodDetailsPromptpayBuilder();
  // TODO add properties to the builder and call build()

  group(PaymentMethodDetailsPromptpay, () {
    // Bill reference generated by PromptPay
    // String reference
    test('to test the property `reference`', () async {
      // TODO
    });

  });
}
