import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for PaymentMethodDetailsFpx
void main() {
  final instance = PaymentMethodDetailsFpxBuilder();
  // TODO add properties to the builder and call build()

  group(PaymentMethodDetailsFpx, () {
    // The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
    // String bank
    test('to test the property `bank`', () async {
      // TODO
    });

    // Unique transaction id generated by FPX for every request from the merchant
    // String transactionId
    test('to test the property `transactionId`', () async {
      // TODO
    });

  });
}
