import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for PaymentMethodDetailsPix
void main() {
  final instance = PaymentMethodDetailsPixBuilder();
  // TODO add properties to the builder and call build()

  group(PaymentMethodDetailsPix, () {
    // Unique transaction id generated by BCB
    // String bankTransactionId
    test('to test the property `bankTransactionId`', () async {
      // TODO
    });

  });
}
