import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for SetupIntentPaymentMethodOptionsPaypal1
void main() {
  final instance = SetupIntentPaymentMethodOptionsPaypal1Builder();
  // TODO add properties to the builder and call build()

  group(SetupIntentPaymentMethodOptionsPaypal1, () {
    // The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
    // String billingAgreementId
    test('to test the property `billingAgreementId`', () async {
      // TODO
    });

    // Bank account verification method.
    // String verificationMethod
    test('to test the property `verificationMethod`', () async {
      // TODO
    });

  });
}
