import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for SetupIntentPaymentMethodOptionsPaypal
void main() {
  final instance = SetupIntentPaymentMethodOptionsPaypalBuilder();
  // TODO add properties to the builder and call build()

  group(SetupIntentPaymentMethodOptionsPaypal, () {
    // The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
    // String billingAgreementId
    test('to test the property `billingAgreementId`', () async {
      // TODO
    });

  });
}
