import 'package:test/test.dart';
import 'package:stripe_dart_sdk/stripe_dart_sdk.dart';

// tests for SubscriptionsResourceSubscriptionInvoiceSettings
void main() {
  final instance = SubscriptionsResourceSubscriptionInvoiceSettingsBuilder();
  // TODO add properties to the builder and call build()

  group(SubscriptionsResourceSubscriptionInvoiceSettings, () {
    // The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.
    // BuiltList<InvoiceAccountTaxIdsInner> accountTaxIds
    test('to test the property `accountTaxIds`', () async {
      // TODO
    });

    // ConnectAccountReference issuer
    test('to test the property `issuer`', () async {
      // TODO
    });

  });
}
