//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class MandatePaypal {
  /// Returns a new [MandatePaypal] instance.
  MandatePaypal({
    this.billingAgreementId,
    this.payerId,
  });

  /// The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
  String? billingAgreementId;

  /// PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
  String? payerId;

  @override
  bool operator ==(Object other) => identical(this, other) || other is MandatePaypal &&
    other.billingAgreementId == billingAgreementId &&
    other.payerId == payerId;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (billingAgreementId == null ? 0 : billingAgreementId!.hashCode) +
    (payerId == null ? 0 : payerId!.hashCode);

  @override
  String toString() => 'MandatePaypal[billingAgreementId=$billingAgreementId, payerId=$payerId]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (this.billingAgreementId != null) {
      json[r'billing_agreement_id'] = this.billingAgreementId;
    } else {
      json[r'billing_agreement_id'] = null;
    }
    if (this.payerId != null) {
      json[r'payer_id'] = this.payerId;
    } else {
      json[r'payer_id'] = null;
    }
    return json;
  }

  /// Returns a new [MandatePaypal] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static MandatePaypal? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "MandatePaypal[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "MandatePaypal[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return MandatePaypal(
        billingAgreementId: mapValueOfType<String>(json, r'billing_agreement_id'),
        payerId: mapValueOfType<String>(json, r'payer_id'),
      );
    }
    return null;
  }

  static List<MandatePaypal> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <MandatePaypal>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = MandatePaypal.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, MandatePaypal> mapFromJson(dynamic json) {
    final map = <String, MandatePaypal>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = MandatePaypal.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of MandatePaypal-objects as value to a dart map
  static Map<String, List<MandatePaypal>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<MandatePaypal>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = MandatePaypal.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
  };
}

