//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class PaymentMethodDetailsFpx {
  /// Returns a new [PaymentMethodDetailsFpx] instance.
  PaymentMethodDetailsFpx({
    required this.bank,
    this.transactionId,
  });

  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  PaymentMethodDetailsFpxBankEnum bank;

  /// Unique transaction id generated by FPX for every request from the merchant
  String? transactionId;

  @override
  bool operator ==(Object other) => identical(this, other) || other is PaymentMethodDetailsFpx &&
    other.bank == bank &&
    other.transactionId == transactionId;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (bank.hashCode) +
    (transactionId == null ? 0 : transactionId!.hashCode);

  @override
  String toString() => 'PaymentMethodDetailsFpx[bank=$bank, transactionId=$transactionId]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'bank'] = this.bank;
    if (this.transactionId != null) {
      json[r'transaction_id'] = this.transactionId;
    } else {
      json[r'transaction_id'] = null;
    }
    return json;
  }

  /// Returns a new [PaymentMethodDetailsFpx] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static PaymentMethodDetailsFpx? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "PaymentMethodDetailsFpx[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "PaymentMethodDetailsFpx[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return PaymentMethodDetailsFpx(
        bank: PaymentMethodDetailsFpxBankEnum.fromJson(json[r'bank'])!,
        transactionId: mapValueOfType<String>(json, r'transaction_id'),
      );
    }
    return null;
  }

  static List<PaymentMethodDetailsFpx> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <PaymentMethodDetailsFpx>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = PaymentMethodDetailsFpx.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, PaymentMethodDetailsFpx> mapFromJson(dynamic json) {
    final map = <String, PaymentMethodDetailsFpx>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = PaymentMethodDetailsFpx.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of PaymentMethodDetailsFpx-objects as value to a dart map
  static Map<String, List<PaymentMethodDetailsFpx>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<PaymentMethodDetailsFpx>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = PaymentMethodDetailsFpx.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'bank',
  };
}

/// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
class PaymentMethodDetailsFpxBankEnum {
  /// Instantiate a new enum with the provided [value].
  const PaymentMethodDetailsFpxBankEnum._(this.value);

  /// The underlying value of this enum member.
  final String value;

  @override
  String toString() => value;

  String toJson() => value;

  static const affinBank = PaymentMethodDetailsFpxBankEnum._(r'affin_bank');
  static const agrobank = PaymentMethodDetailsFpxBankEnum._(r'agrobank');
  static const allianceBank = PaymentMethodDetailsFpxBankEnum._(r'alliance_bank');
  static const ambank = PaymentMethodDetailsFpxBankEnum._(r'ambank');
  static const bankIslam = PaymentMethodDetailsFpxBankEnum._(r'bank_islam');
  static const bankMuamalat = PaymentMethodDetailsFpxBankEnum._(r'bank_muamalat');
  static const bankOfChina = PaymentMethodDetailsFpxBankEnum._(r'bank_of_china');
  static const bankRakyat = PaymentMethodDetailsFpxBankEnum._(r'bank_rakyat');
  static const bsn = PaymentMethodDetailsFpxBankEnum._(r'bsn');
  static const cimb = PaymentMethodDetailsFpxBankEnum._(r'cimb');
  static const deutscheBank = PaymentMethodDetailsFpxBankEnum._(r'deutsche_bank');
  static const hongLeongBank = PaymentMethodDetailsFpxBankEnum._(r'hong_leong_bank');
  static const hsbc = PaymentMethodDetailsFpxBankEnum._(r'hsbc');
  static const kfh = PaymentMethodDetailsFpxBankEnum._(r'kfh');
  static const maybank2e = PaymentMethodDetailsFpxBankEnum._(r'maybank2e');
  static const maybank2u = PaymentMethodDetailsFpxBankEnum._(r'maybank2u');
  static const ocbc = PaymentMethodDetailsFpxBankEnum._(r'ocbc');
  static const pbEnterprise = PaymentMethodDetailsFpxBankEnum._(r'pb_enterprise');
  static const publicBank = PaymentMethodDetailsFpxBankEnum._(r'public_bank');
  static const rhb = PaymentMethodDetailsFpxBankEnum._(r'rhb');
  static const standardChartered = PaymentMethodDetailsFpxBankEnum._(r'standard_chartered');
  static const uob = PaymentMethodDetailsFpxBankEnum._(r'uob');

  /// List of all possible values in this [enum][PaymentMethodDetailsFpxBankEnum].
  static const values = <PaymentMethodDetailsFpxBankEnum>[
    affinBank,
    agrobank,
    allianceBank,
    ambank,
    bankIslam,
    bankMuamalat,
    bankOfChina,
    bankRakyat,
    bsn,
    cimb,
    deutscheBank,
    hongLeongBank,
    hsbc,
    kfh,
    maybank2e,
    maybank2u,
    ocbc,
    pbEnterprise,
    publicBank,
    rhb,
    standardChartered,
    uob,
  ];

  static PaymentMethodDetailsFpxBankEnum? fromJson(dynamic value) => PaymentMethodDetailsFpxBankEnumTypeTransformer().decode(value);

  static List<PaymentMethodDetailsFpxBankEnum> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <PaymentMethodDetailsFpxBankEnum>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = PaymentMethodDetailsFpxBankEnum.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }
}

/// Transformation class that can [encode] an instance of [PaymentMethodDetailsFpxBankEnum] to String,
/// and [decode] dynamic data back to [PaymentMethodDetailsFpxBankEnum].
class PaymentMethodDetailsFpxBankEnumTypeTransformer {
  factory PaymentMethodDetailsFpxBankEnumTypeTransformer() => _instance ??= const PaymentMethodDetailsFpxBankEnumTypeTransformer._();

  const PaymentMethodDetailsFpxBankEnumTypeTransformer._();

  String encode(PaymentMethodDetailsFpxBankEnum data) => data.value;

  /// Decodes a [dynamic value][data] to a PaymentMethodDetailsFpxBankEnum.
  ///
  /// If [allowNull] is true and the [dynamic value][data] cannot be decoded successfully,
  /// then null is returned. However, if [allowNull] is false and the [dynamic value][data]
  /// cannot be decoded successfully, then an [UnimplementedError] is thrown.
  ///
  /// The [allowNull] is very handy when an API changes and a new enum value is added or removed,
  /// and users are still using an old app with the old code.
  PaymentMethodDetailsFpxBankEnum? decode(dynamic data, {bool allowNull = true}) {
    if (data != null) {
      switch (data) {
        case r'affin_bank': return PaymentMethodDetailsFpxBankEnum.affinBank;
        case r'agrobank': return PaymentMethodDetailsFpxBankEnum.agrobank;
        case r'alliance_bank': return PaymentMethodDetailsFpxBankEnum.allianceBank;
        case r'ambank': return PaymentMethodDetailsFpxBankEnum.ambank;
        case r'bank_islam': return PaymentMethodDetailsFpxBankEnum.bankIslam;
        case r'bank_muamalat': return PaymentMethodDetailsFpxBankEnum.bankMuamalat;
        case r'bank_of_china': return PaymentMethodDetailsFpxBankEnum.bankOfChina;
        case r'bank_rakyat': return PaymentMethodDetailsFpxBankEnum.bankRakyat;
        case r'bsn': return PaymentMethodDetailsFpxBankEnum.bsn;
        case r'cimb': return PaymentMethodDetailsFpxBankEnum.cimb;
        case r'deutsche_bank': return PaymentMethodDetailsFpxBankEnum.deutscheBank;
        case r'hong_leong_bank': return PaymentMethodDetailsFpxBankEnum.hongLeongBank;
        case r'hsbc': return PaymentMethodDetailsFpxBankEnum.hsbc;
        case r'kfh': return PaymentMethodDetailsFpxBankEnum.kfh;
        case r'maybank2e': return PaymentMethodDetailsFpxBankEnum.maybank2e;
        case r'maybank2u': return PaymentMethodDetailsFpxBankEnum.maybank2u;
        case r'ocbc': return PaymentMethodDetailsFpxBankEnum.ocbc;
        case r'pb_enterprise': return PaymentMethodDetailsFpxBankEnum.pbEnterprise;
        case r'public_bank': return PaymentMethodDetailsFpxBankEnum.publicBank;
        case r'rhb': return PaymentMethodDetailsFpxBankEnum.rhb;
        case r'standard_chartered': return PaymentMethodDetailsFpxBankEnum.standardChartered;
        case r'uob': return PaymentMethodDetailsFpxBankEnum.uob;
        default:
          if (!allowNull) {
            throw ArgumentError('Unknown enum value to decode: $data');
          }
      }
    }
    return null;
  }

  /// Singleton [PaymentMethodDetailsFpxBankEnumTypeTransformer] instance.
  static PaymentMethodDetailsFpxBankEnumTypeTransformer? _instance;
}


