//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class PaymentMethodDetailsPaypal {
  /// Returns a new [PaymentMethodDetailsPaypal] instance.
  PaymentMethodDetailsPaypal({
    this.country,
    this.payerEmail,
    this.payerId,
    this.payerName,
    this.sellerProtection,
    this.transactionId,
  });

  /// Two-letter ISO code representing the buyer's country. Values are provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
  String? country;

  /// Owner's email. Values are provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
  String? payerEmail;

  /// PayPal account PayerID. This identifier uniquely identifies the PayPal customer.
  String? payerId;

  /// Owner's full name. Values provided by PayPal directly (if supported) at the time of authorization or settlement. They cannot be set or mutated.
  String? payerName;

  PaypalSellerProtection? sellerProtection;

  /// A unique ID generated by PayPal for this transaction.
  String? transactionId;

  @override
  bool operator ==(Object other) => identical(this, other) || other is PaymentMethodDetailsPaypal &&
    other.country == country &&
    other.payerEmail == payerEmail &&
    other.payerId == payerId &&
    other.payerName == payerName &&
    other.sellerProtection == sellerProtection &&
    other.transactionId == transactionId;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (country == null ? 0 : country!.hashCode) +
    (payerEmail == null ? 0 : payerEmail!.hashCode) +
    (payerId == null ? 0 : payerId!.hashCode) +
    (payerName == null ? 0 : payerName!.hashCode) +
    (sellerProtection == null ? 0 : sellerProtection!.hashCode) +
    (transactionId == null ? 0 : transactionId!.hashCode);

  @override
  String toString() => 'PaymentMethodDetailsPaypal[country=$country, payerEmail=$payerEmail, payerId=$payerId, payerName=$payerName, sellerProtection=$sellerProtection, transactionId=$transactionId]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (this.country != null) {
      json[r'country'] = this.country;
    } else {
      json[r'country'] = null;
    }
    if (this.payerEmail != null) {
      json[r'payer_email'] = this.payerEmail;
    } else {
      json[r'payer_email'] = null;
    }
    if (this.payerId != null) {
      json[r'payer_id'] = this.payerId;
    } else {
      json[r'payer_id'] = null;
    }
    if (this.payerName != null) {
      json[r'payer_name'] = this.payerName;
    } else {
      json[r'payer_name'] = null;
    }
    if (this.sellerProtection != null) {
      json[r'seller_protection'] = this.sellerProtection;
    } else {
      json[r'seller_protection'] = null;
    }
    if (this.transactionId != null) {
      json[r'transaction_id'] = this.transactionId;
    } else {
      json[r'transaction_id'] = null;
    }
    return json;
  }

  /// Returns a new [PaymentMethodDetailsPaypal] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static PaymentMethodDetailsPaypal? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "PaymentMethodDetailsPaypal[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "PaymentMethodDetailsPaypal[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return PaymentMethodDetailsPaypal(
        country: mapValueOfType<String>(json, r'country'),
        payerEmail: mapValueOfType<String>(json, r'payer_email'),
        payerId: mapValueOfType<String>(json, r'payer_id'),
        payerName: mapValueOfType<String>(json, r'payer_name'),
        sellerProtection: PaypalSellerProtection.fromJson(json[r'seller_protection']),
        transactionId: mapValueOfType<String>(json, r'transaction_id'),
      );
    }
    return null;
  }

  static List<PaymentMethodDetailsPaypal> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <PaymentMethodDetailsPaypal>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = PaymentMethodDetailsPaypal.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, PaymentMethodDetailsPaypal> mapFromJson(dynamic json) {
    final map = <String, PaymentMethodDetailsPaypal>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = PaymentMethodDetailsPaypal.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of PaymentMethodDetailsPaypal-objects as value to a dart map
  static Map<String, List<PaymentMethodDetailsPaypal>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<PaymentMethodDetailsPaypal>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = PaymentMethodDetailsPaypal.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
  };
}

