//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of openapi.api;

class SubscriptionsResourceSubscriptionInvoiceSettings {
  /// Returns a new [SubscriptionsResourceSubscriptionInvoiceSettings] instance.
  SubscriptionsResourceSubscriptionInvoiceSettings({
    this.accountTaxIds = const [],
    required this.issuer,
  });

  /// The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.
  List<InvoiceAccountTaxIdsInner>? accountTaxIds;

  ConnectAccountReference issuer;

  @override
  bool operator ==(Object other) => identical(this, other) || other is SubscriptionsResourceSubscriptionInvoiceSettings &&
    _deepEquality.equals(other.accountTaxIds, accountTaxIds) &&
    other.issuer == issuer;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (accountTaxIds == null ? 0 : accountTaxIds!.hashCode) +
    (issuer.hashCode);

  @override
  String toString() => 'SubscriptionsResourceSubscriptionInvoiceSettings[accountTaxIds=$accountTaxIds, issuer=$issuer]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
    if (this.accountTaxIds != null) {
      json[r'account_tax_ids'] = this.accountTaxIds;
    } else {
      json[r'account_tax_ids'] = null;
    }
      json[r'issuer'] = this.issuer;
    return json;
  }

  /// Returns a new [SubscriptionsResourceSubscriptionInvoiceSettings] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static SubscriptionsResourceSubscriptionInvoiceSettings? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "SubscriptionsResourceSubscriptionInvoiceSettings[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "SubscriptionsResourceSubscriptionInvoiceSettings[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return SubscriptionsResourceSubscriptionInvoiceSettings(
        accountTaxIds: InvoiceAccountTaxIdsInner.listFromJson(json[r'account_tax_ids']),
        issuer: ConnectAccountReference.fromJson(json[r'issuer'])!,
      );
    }
    return null;
  }

  static List<SubscriptionsResourceSubscriptionInvoiceSettings> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <SubscriptionsResourceSubscriptionInvoiceSettings>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = SubscriptionsResourceSubscriptionInvoiceSettings.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, SubscriptionsResourceSubscriptionInvoiceSettings> mapFromJson(dynamic json) {
    final map = <String, SubscriptionsResourceSubscriptionInvoiceSettings>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = SubscriptionsResourceSubscriptionInvoiceSettings.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of SubscriptionsResourceSubscriptionInvoiceSettings-objects as value to a dart map
  static Map<String, List<SubscriptionsResourceSubscriptionInvoiceSettings>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<SubscriptionsResourceSubscriptionInvoiceSettings>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = SubscriptionsResourceSubscriptionInvoiceSettings.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
    'issuer',
  };
}

