//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'payment_method_details_grabpay.g.dart';

/// 
///
/// Properties:
/// * [transactionId] - Unique transaction id generated by GrabPay
@BuiltValue()
abstract class PaymentMethodDetailsGrabpay implements Built<PaymentMethodDetailsGrabpay, PaymentMethodDetailsGrabpayBuilder> {
  /// Unique transaction id generated by GrabPay
  @BuiltValueField(wireName: r'transaction_id')
  String? get transactionId;

  PaymentMethodDetailsGrabpay._();

  factory PaymentMethodDetailsGrabpay([void updates(PaymentMethodDetailsGrabpayBuilder b)]) = _$PaymentMethodDetailsGrabpay;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(PaymentMethodDetailsGrabpayBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<PaymentMethodDetailsGrabpay> get serializer => _$PaymentMethodDetailsGrabpaySerializer();
}

class _$PaymentMethodDetailsGrabpaySerializer implements PrimitiveSerializer<PaymentMethodDetailsGrabpay> {
  @override
  final Iterable<Type> types = const [PaymentMethodDetailsGrabpay, _$PaymentMethodDetailsGrabpay];

  @override
  final String wireName = r'PaymentMethodDetailsGrabpay';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    PaymentMethodDetailsGrabpay object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    if (object.transactionId != null) {
      yield r'transaction_id';
      yield serializers.serialize(
        object.transactionId,
        specifiedType: const FullType.nullable(String),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    PaymentMethodDetailsGrabpay object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required PaymentMethodDetailsGrabpayBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'transaction_id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.transactionId = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  PaymentMethodDetailsGrabpay deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = PaymentMethodDetailsGrabpayBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

