//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'payment_method_details_fpx.g.dart';

/// 
///
/// Properties:
/// * [bank] - The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
/// * [transactionId] - Unique transaction id generated by FPX for every request from the merchant
@BuiltValue()
abstract class PaymentMethodDetailsFpx implements Built<PaymentMethodDetailsFpx, PaymentMethodDetailsFpxBuilder> {
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueField(wireName: r'bank')
  PaymentMethodDetailsFpxBankEnum get bank;
  // enum bankEnum {  affin_bank,  agrobank,  alliance_bank,  ambank,  bank_islam,  bank_muamalat,  bank_of_china,  bank_rakyat,  bsn,  cimb,  deutsche_bank,  hong_leong_bank,  hsbc,  kfh,  maybank2e,  maybank2u,  ocbc,  pb_enterprise,  public_bank,  rhb,  standard_chartered,  uob,  };

  /// Unique transaction id generated by FPX for every request from the merchant
  @BuiltValueField(wireName: r'transaction_id')
  String? get transactionId;

  PaymentMethodDetailsFpx._();

  factory PaymentMethodDetailsFpx([void updates(PaymentMethodDetailsFpxBuilder b)]) = _$PaymentMethodDetailsFpx;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(PaymentMethodDetailsFpxBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<PaymentMethodDetailsFpx> get serializer => _$PaymentMethodDetailsFpxSerializer();
}

class _$PaymentMethodDetailsFpxSerializer implements PrimitiveSerializer<PaymentMethodDetailsFpx> {
  @override
  final Iterable<Type> types = const [PaymentMethodDetailsFpx, _$PaymentMethodDetailsFpx];

  @override
  final String wireName = r'PaymentMethodDetailsFpx';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    PaymentMethodDetailsFpx object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'bank';
    yield serializers.serialize(
      object.bank,
      specifiedType: const FullType(PaymentMethodDetailsFpxBankEnum),
    );
    if (object.transactionId != null) {
      yield r'transaction_id';
      yield serializers.serialize(
        object.transactionId,
        specifiedType: const FullType.nullable(String),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    PaymentMethodDetailsFpx object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required PaymentMethodDetailsFpxBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'bank':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(PaymentMethodDetailsFpxBankEnum),
          ) as PaymentMethodDetailsFpxBankEnum;
          result.bank = valueDes;
          break;
        case r'transaction_id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.transactionId = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  PaymentMethodDetailsFpx deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = PaymentMethodDetailsFpxBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

class PaymentMethodDetailsFpxBankEnum extends EnumClass {

  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'affin_bank')
  static const PaymentMethodDetailsFpxBankEnum affinBank = _$paymentMethodDetailsFpxBankEnum_affinBank;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'agrobank')
  static const PaymentMethodDetailsFpxBankEnum agrobank = _$paymentMethodDetailsFpxBankEnum_agrobank;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'alliance_bank')
  static const PaymentMethodDetailsFpxBankEnum allianceBank = _$paymentMethodDetailsFpxBankEnum_allianceBank;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'ambank')
  static const PaymentMethodDetailsFpxBankEnum ambank = _$paymentMethodDetailsFpxBankEnum_ambank;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'bank_islam')
  static const PaymentMethodDetailsFpxBankEnum bankIslam = _$paymentMethodDetailsFpxBankEnum_bankIslam;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'bank_muamalat')
  static const PaymentMethodDetailsFpxBankEnum bankMuamalat = _$paymentMethodDetailsFpxBankEnum_bankMuamalat;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'bank_of_china')
  static const PaymentMethodDetailsFpxBankEnum bankOfChina = _$paymentMethodDetailsFpxBankEnum_bankOfChina;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'bank_rakyat')
  static const PaymentMethodDetailsFpxBankEnum bankRakyat = _$paymentMethodDetailsFpxBankEnum_bankRakyat;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'bsn')
  static const PaymentMethodDetailsFpxBankEnum bsn = _$paymentMethodDetailsFpxBankEnum_bsn;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'cimb')
  static const PaymentMethodDetailsFpxBankEnum cimb = _$paymentMethodDetailsFpxBankEnum_cimb;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'deutsche_bank')
  static const PaymentMethodDetailsFpxBankEnum deutscheBank = _$paymentMethodDetailsFpxBankEnum_deutscheBank;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'hong_leong_bank')
  static const PaymentMethodDetailsFpxBankEnum hongLeongBank = _$paymentMethodDetailsFpxBankEnum_hongLeongBank;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'hsbc')
  static const PaymentMethodDetailsFpxBankEnum hsbc = _$paymentMethodDetailsFpxBankEnum_hsbc;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'kfh')
  static const PaymentMethodDetailsFpxBankEnum kfh = _$paymentMethodDetailsFpxBankEnum_kfh;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'maybank2e')
  static const PaymentMethodDetailsFpxBankEnum maybank2e = _$paymentMethodDetailsFpxBankEnum_maybank2e;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'maybank2u')
  static const PaymentMethodDetailsFpxBankEnum maybank2u = _$paymentMethodDetailsFpxBankEnum_maybank2u;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'ocbc')
  static const PaymentMethodDetailsFpxBankEnum ocbc = _$paymentMethodDetailsFpxBankEnum_ocbc;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'pb_enterprise')
  static const PaymentMethodDetailsFpxBankEnum pbEnterprise = _$paymentMethodDetailsFpxBankEnum_pbEnterprise;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'public_bank')
  static const PaymentMethodDetailsFpxBankEnum publicBank = _$paymentMethodDetailsFpxBankEnum_publicBank;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'rhb')
  static const PaymentMethodDetailsFpxBankEnum rhb = _$paymentMethodDetailsFpxBankEnum_rhb;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'standard_chartered')
  static const PaymentMethodDetailsFpxBankEnum standardChartered = _$paymentMethodDetailsFpxBankEnum_standardChartered;
  /// The customer's bank. Can be one of `affin_bank`, `agrobank`, `alliance_bank`, `ambank`, `bank_islam`, `bank_muamalat`, `bank_rakyat`, `bsn`, `cimb`, `hong_leong_bank`, `hsbc`, `kfh`, `maybank2u`, `ocbc`, `public_bank`, `rhb`, `standard_chartered`, `uob`, `deutsche_bank`, `maybank2e`, `pb_enterprise`, or `bank_of_china`.
  @BuiltValueEnumConst(wireName: r'uob')
  static const PaymentMethodDetailsFpxBankEnum uob = _$paymentMethodDetailsFpxBankEnum_uob;

  static Serializer<PaymentMethodDetailsFpxBankEnum> get serializer => _$paymentMethodDetailsFpxBankEnumSerializer;

  const PaymentMethodDetailsFpxBankEnum._(String name): super(name);

  static BuiltSet<PaymentMethodDetailsFpxBankEnum> get values => _$paymentMethodDetailsFpxBankEnumValues;
  static PaymentMethodDetailsFpxBankEnum valueOf(String name) => _$paymentMethodDetailsFpxBankEnumValueOf(name);
}

