//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:stripe_dart_sdk/src/model/payment_method_nz_bank_account.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_card.dart';
import 'package:stripe_dart_sdk/src/model/confirmation_tokens_resource_payment_method_preview_customer.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_ideal.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_us_bank_account.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_link.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_klarna.dart';
import 'dart:core';
import 'package:stripe_dart_sdk/src/model/payment_method_kr_card.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_au_becs_debit.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_card_present.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_sofort.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_fpx.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_interac_present.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_bacs_debit.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_naver_pay.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_p24.dart';
import 'package:stripe_dart_sdk/src/model/payment_method.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_eps.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_acss_debit.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_sepa_debit.dart';
import 'package:built_collection/built_collection.dart';
import 'package:stripe_dart_sdk/src/model/radar_radar_options.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_cashapp.dart';
import 'package:stripe_dart_sdk/src/model/billing_details.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_boleto.dart';
import 'package:built_value/json_object.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_paypal.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:one_of/any_of.dart';

part 'payment_method_details_bancontact_generated_sepa_debit.g.dart';

/// The ID of the SEPA Direct Debit PaymentMethod which was generated by this Charge.
///
/// Properties:
/// * [acssDebit] 
/// * [affirm] - 
/// * [afterpayClearpay] - 
/// * [alipay] - 
/// * [allowRedisplay] - This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
/// * [alma] - 
/// * [amazonPay] - 
/// * [auBecsDebit] 
/// * [bacsDebit] 
/// * [bancontact] - 
/// * [billie] - 
/// * [billingDetails] 
/// * [blik] - 
/// * [boleto] 
/// * [card] 
/// * [cardPresent] 
/// * [cashapp] 
/// * [created] - Time at which the object was created. Measured in seconds since the Unix epoch.
/// * [crypto] - 
/// * [customer] 
/// * [customerBalance] - 
/// * [eps] 
/// * [fpx] 
/// * [giropay] - 
/// * [grabpay] - 
/// * [id] - Unique identifier for the object.
/// * [ideal] 
/// * [interacPresent] 
/// * [kakaoPay] - 
/// * [klarna] 
/// * [konbini] - 
/// * [krCard] 
/// * [link] 
/// * [livemode] - Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
/// * [metadata] - Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
/// * [mobilepay] - 
/// * [multibanco] - 
/// * [naverPay] 
/// * [nzBankAccount] 
/// * [object] - String representing the object's type. Objects of the same type share the same value.
/// * [oxxo] - 
/// * [p24] 
/// * [payByBank] - 
/// * [payco] - 
/// * [paynow] - 
/// * [paypal] 
/// * [pix] - 
/// * [promptpay] - 
/// * [radarOptions] 
/// * [revolutPay] - 
/// * [samsungPay] - 
/// * [satispay] - 
/// * [sepaDebit] 
/// * [sofort] 
/// * [swish] - 
/// * [twint] - 
/// * [type] - The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
/// * [usBankAccount] 
/// * [wechatPay] - 
/// * [zip] - 
@BuiltValue()
abstract class PaymentMethodDetailsBancontactGeneratedSepaDebit implements Built<PaymentMethodDetailsBancontactGeneratedSepaDebit, PaymentMethodDetailsBancontactGeneratedSepaDebitBuilder> {
  /// Any Of [PaymentMethod], [String]
  AnyOf get anyOf;

  PaymentMethodDetailsBancontactGeneratedSepaDebit._();

  factory PaymentMethodDetailsBancontactGeneratedSepaDebit([void updates(PaymentMethodDetailsBancontactGeneratedSepaDebitBuilder b)]) = _$PaymentMethodDetailsBancontactGeneratedSepaDebit;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(PaymentMethodDetailsBancontactGeneratedSepaDebitBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<PaymentMethodDetailsBancontactGeneratedSepaDebit> get serializer => _$PaymentMethodDetailsBancontactGeneratedSepaDebitSerializer();
}

class _$PaymentMethodDetailsBancontactGeneratedSepaDebitSerializer implements PrimitiveSerializer<PaymentMethodDetailsBancontactGeneratedSepaDebit> {
  @override
  final Iterable<Type> types = const [PaymentMethodDetailsBancontactGeneratedSepaDebit, _$PaymentMethodDetailsBancontactGeneratedSepaDebit];

  @override
  final String wireName = r'PaymentMethodDetailsBancontactGeneratedSepaDebit';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    PaymentMethodDetailsBancontactGeneratedSepaDebit object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
  }

  @override
  Object serialize(
    Serializers serializers,
    PaymentMethodDetailsBancontactGeneratedSepaDebit object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final anyOf = object.anyOf;
    return serializers.serialize(anyOf, specifiedType: FullType(AnyOf, anyOf.valueTypes.map((type) => FullType(type)).toList()))!;
  }

  @override
  PaymentMethodDetailsBancontactGeneratedSepaDebit deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = PaymentMethodDetailsBancontactGeneratedSepaDebitBuilder();
    Object? anyOfDataSrc;
    final targetType = const FullType(AnyOf, [FullType(String), FullType(PaymentMethod), ]);
    anyOfDataSrc = serialized;
    result.anyOf = serializers.deserialize(anyOfDataSrc, specifiedType: targetType) as AnyOf;
    return result.build();
  }
}

class PaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum extends EnumClass {

  /// This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
  @BuiltValueEnumConst(wireName: r'always')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum always = _$paymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum_always;
  /// This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
  @BuiltValueEnumConst(wireName: r'limited')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum limited = _$paymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum_limited;
  /// This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
  @BuiltValueEnumConst(wireName: r'unspecified')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum unspecified = _$paymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum_unspecified;

  static Serializer<PaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum> get serializer => _$paymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnumSerializer;

  const PaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum._(String name): super(name);

  static BuiltSet<PaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum> get values => _$paymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnumValues;
  static PaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum valueOf(String name) => _$paymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnumValueOf(name);
}

class PaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum extends EnumClass {

  /// String representing the object's type. Objects of the same type share the same value.
  @BuiltValueEnumConst(wireName: r'payment_method')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum paymentMethod = _$paymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum_paymentMethod;

  static Serializer<PaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum> get serializer => _$paymentMethodDetailsBancontactGeneratedSepaDebitObjectEnumSerializer;

  const PaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum._(String name): super(name);

  static BuiltSet<PaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum> get values => _$paymentMethodDetailsBancontactGeneratedSepaDebitObjectEnumValues;
  static PaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum valueOf(String name) => _$paymentMethodDetailsBancontactGeneratedSepaDebitObjectEnumValueOf(name);
}

class PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum extends EnumClass {

  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'acss_debit')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum acssDebit = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_acssDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'affirm')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum affirm = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_affirm;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'afterpay_clearpay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum afterpayClearpay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_afterpayClearpay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'alipay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum alipay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_alipay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'alma')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum alma = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_alma;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'amazon_pay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum amazonPay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_amazonPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'au_becs_debit')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum auBecsDebit = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_auBecsDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'bacs_debit')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum bacsDebit = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_bacsDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'bancontact')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum bancontact = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_bancontact;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'billie')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum billie = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_billie;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'blik')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum blik = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_blik;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'boleto')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum boleto = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_boleto;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'card')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum card = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_card;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'card_present')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum cardPresent = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_cardPresent;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'cashapp')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum cashapp = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_cashapp;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'crypto')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum crypto = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_crypto;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'customer_balance')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum customerBalance = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_customerBalance;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'eps')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum eps = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_eps;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'fpx')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum fpx = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_fpx;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'giropay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum giropay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_giropay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'grabpay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum grabpay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_grabpay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'ideal')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum ideal = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_ideal;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'interac_present')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum interacPresent = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_interacPresent;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'kakao_pay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum kakaoPay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_kakaoPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'klarna')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum klarna = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_klarna;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'konbini')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum konbini = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_konbini;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'kr_card')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum krCard = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_krCard;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'link')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum link = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_link;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'mobilepay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum mobilepay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_mobilepay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'multibanco')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum multibanco = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_multibanco;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'naver_pay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum naverPay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_naverPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'nz_bank_account')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum nzBankAccount = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_nzBankAccount;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'oxxo')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum oxxo = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_oxxo;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'p24')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum p24 = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_p24;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'pay_by_bank')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum payByBank = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_payByBank;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'payco')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum payco = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_payco;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'paynow')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum paynow = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_paynow;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'paypal')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum paypal = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_paypal;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'pix')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum pix = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_pix;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'promptpay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum promptpay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_promptpay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'revolut_pay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum revolutPay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_revolutPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'samsung_pay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum samsungPay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_samsungPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'satispay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum satispay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_satispay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'sepa_debit')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum sepaDebit = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_sepaDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'sofort')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum sofort = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_sofort;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'swish')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum swish = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_swish;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'twint')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum twint = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_twint;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'us_bank_account')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum usBankAccount = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_usBankAccount;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'wechat_pay')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum wechatPay = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_wechatPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'zip')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum zip = _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_zip;

  static Serializer<PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum> get serializer => _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnumSerializer;

  const PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum._(String name): super(name);

  static BuiltSet<PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum> get values => _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnumValues;
  static PaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum valueOf(String name) => _$paymentMethodDetailsBancontactGeneratedSepaDebitTypeEnumValueOf(name);
}

