//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:stripe_dart_sdk/src/model/customer_acceptance.dart';
import 'package:built_collection/built_collection.dart';
import 'package:stripe_dart_sdk/src/model/mandate_payment_method_details.dart';
import 'package:stripe_dart_sdk/src/model/mandate.dart';
import 'package:stripe_dart_sdk/src/model/mandate_single_use.dart';
import 'package:built_value/json_object.dart';
import 'package:stripe_dart_sdk/src/model/mandate_payment_method.dart';
import 'dart:core';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:one_of/any_of.dart';

part 'payment_method_details_bancontact_generated_sepa_debit_mandate.g.dart';

/// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this Charge.
///
/// Properties:
/// * [customerAcceptance] 
/// * [id] - Unique identifier for the object.
/// * [livemode] - Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
/// * [multiUse] - 
/// * [object] - String representing the object's type. Objects of the same type share the same value.
/// * [onBehalfOf] - The account (if any) that the mandate is intended for.
/// * [paymentMethod] 
/// * [paymentMethodDetails] 
/// * [singleUse] 
/// * [status] - The mandate status indicates whether or not you can use it to initiate a payment.
/// * [type] - The type of the mandate.
@BuiltValue()
abstract class PaymentMethodDetailsBancontactGeneratedSepaDebitMandate implements Built<PaymentMethodDetailsBancontactGeneratedSepaDebitMandate, PaymentMethodDetailsBancontactGeneratedSepaDebitMandateBuilder> {
  /// Any Of [Mandate], [String]
  AnyOf get anyOf;

  PaymentMethodDetailsBancontactGeneratedSepaDebitMandate._();

  factory PaymentMethodDetailsBancontactGeneratedSepaDebitMandate([void updates(PaymentMethodDetailsBancontactGeneratedSepaDebitMandateBuilder b)]) = _$PaymentMethodDetailsBancontactGeneratedSepaDebitMandate;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(PaymentMethodDetailsBancontactGeneratedSepaDebitMandateBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<PaymentMethodDetailsBancontactGeneratedSepaDebitMandate> get serializer => _$PaymentMethodDetailsBancontactGeneratedSepaDebitMandateSerializer();
}

class _$PaymentMethodDetailsBancontactGeneratedSepaDebitMandateSerializer implements PrimitiveSerializer<PaymentMethodDetailsBancontactGeneratedSepaDebitMandate> {
  @override
  final Iterable<Type> types = const [PaymentMethodDetailsBancontactGeneratedSepaDebitMandate, _$PaymentMethodDetailsBancontactGeneratedSepaDebitMandate];

  @override
  final String wireName = r'PaymentMethodDetailsBancontactGeneratedSepaDebitMandate';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    PaymentMethodDetailsBancontactGeneratedSepaDebitMandate object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
  }

  @override
  Object serialize(
    Serializers serializers,
    PaymentMethodDetailsBancontactGeneratedSepaDebitMandate object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final anyOf = object.anyOf;
    return serializers.serialize(anyOf, specifiedType: FullType(AnyOf, anyOf.valueTypes.map((type) => FullType(type)).toList()))!;
  }

  @override
  PaymentMethodDetailsBancontactGeneratedSepaDebitMandate deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = PaymentMethodDetailsBancontactGeneratedSepaDebitMandateBuilder();
    Object? anyOfDataSrc;
    final targetType = const FullType(AnyOf, [FullType(String), FullType(Mandate), ]);
    anyOfDataSrc = serialized;
    result.anyOf = serializers.deserialize(anyOfDataSrc, specifiedType: targetType) as AnyOf;
    return result.build();
  }
}

class PaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum extends EnumClass {

  /// String representing the object's type. Objects of the same type share the same value.
  @BuiltValueEnumConst(wireName: r'mandate')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum mandate = _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum_mandate;

  static Serializer<PaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum> get serializer => _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnumSerializer;

  const PaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum._(String name): super(name);

  static BuiltSet<PaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum> get values => _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnumValues;
  static PaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum valueOf(String name) => _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnumValueOf(name);
}

class PaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum extends EnumClass {

  /// The mandate status indicates whether or not you can use it to initiate a payment.
  @BuiltValueEnumConst(wireName: r'active')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum active = _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum_active;
  /// The mandate status indicates whether or not you can use it to initiate a payment.
  @BuiltValueEnumConst(wireName: r'inactive')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum inactive = _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum_inactive;
  /// The mandate status indicates whether or not you can use it to initiate a payment.
  @BuiltValueEnumConst(wireName: r'pending')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum pending = _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum_pending;

  static Serializer<PaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum> get serializer => _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnumSerializer;

  const PaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum._(String name): super(name);

  static BuiltSet<PaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum> get values => _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnumValues;
  static PaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum valueOf(String name) => _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnumValueOf(name);
}

class PaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum extends EnumClass {

  /// The type of the mandate.
  @BuiltValueEnumConst(wireName: r'multi_use')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum multiUse = _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum_multiUse;
  /// The type of the mandate.
  @BuiltValueEnumConst(wireName: r'single_use')
  static const PaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum singleUse = _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum_singleUse;

  static Serializer<PaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum> get serializer => _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnumSerializer;

  const PaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum._(String name): super(name);

  static BuiltSet<PaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum> get values => _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnumValues;
  static PaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum valueOf(String name) => _$paymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnumValueOf(name);
}

