//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'payment_method_details_promptpay.g.dart';

/// 
///
/// Properties:
/// * [reference] - Bill reference generated by PromptPay
@BuiltValue()
abstract class PaymentMethodDetailsPromptpay implements Built<PaymentMethodDetailsPromptpay, PaymentMethodDetailsPromptpayBuilder> {
  /// Bill reference generated by PromptPay
  @BuiltValueField(wireName: r'reference')
  String? get reference;

  PaymentMethodDetailsPromptpay._();

  factory PaymentMethodDetailsPromptpay([void updates(PaymentMethodDetailsPromptpayBuilder b)]) = _$PaymentMethodDetailsPromptpay;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(PaymentMethodDetailsPromptpayBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<PaymentMethodDetailsPromptpay> get serializer => _$PaymentMethodDetailsPromptpaySerializer();
}

class _$PaymentMethodDetailsPromptpaySerializer implements PrimitiveSerializer<PaymentMethodDetailsPromptpay> {
  @override
  final Iterable<Type> types = const [PaymentMethodDetailsPromptpay, _$PaymentMethodDetailsPromptpay];

  @override
  final String wireName = r'PaymentMethodDetailsPromptpay';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    PaymentMethodDetailsPromptpay object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    if (object.reference != null) {
      yield r'reference';
      yield serializers.serialize(
        object.reference,
        specifiedType: const FullType.nullable(String),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    PaymentMethodDetailsPromptpay object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required PaymentMethodDetailsPromptpayBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'reference':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.reference = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  PaymentMethodDetailsPromptpay deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = PaymentMethodDetailsPromptpayBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

