//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:stripe_dart_sdk/src/model/customer_acceptance.dart';
import 'package:built_collection/built_collection.dart';
import 'package:stripe_dart_sdk/src/model/mandate_payment_method_details.dart';
import 'package:stripe_dart_sdk/src/model/mandate.dart';
import 'package:stripe_dart_sdk/src/model/mandate_single_use.dart';
import 'package:built_value/json_object.dart';
import 'package:stripe_dart_sdk/src/model/mandate_payment_method.dart';
import 'dart:core';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:one_of/any_of.dart';

part 'setup_attempt_payment_method_details_bancontact_generated_sepa_debit_mandate.g.dart';

/// The mandate for the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
///
/// Properties:
/// * [customerAcceptance] 
/// * [id] - Unique identifier for the object.
/// * [livemode] - Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
/// * [multiUse] - 
/// * [object] - String representing the object's type. Objects of the same type share the same value.
/// * [onBehalfOf] - The account (if any) that the mandate is intended for.
/// * [paymentMethod] 
/// * [paymentMethodDetails] 
/// * [singleUse] 
/// * [status] - The mandate status indicates whether or not you can use it to initiate a payment.
/// * [type] - The type of the mandate.
@BuiltValue()
abstract class SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate implements Built<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate, SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateBuilder> {
  /// Any Of [Mandate], [String]
  AnyOf get anyOf;

  SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate._();

  factory SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate([void updates(SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateBuilder b)]) = _$SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate> get serializer => _$SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateSerializer();
}

class _$SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateSerializer implements PrimitiveSerializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate> {
  @override
  final Iterable<Type> types = const [SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate, _$SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate];

  @override
  final String wireName = r'SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
  }

  @override
  Object serialize(
    Serializers serializers,
    SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final anyOf = object.anyOf;
    return serializers.serialize(anyOf, specifiedType: FullType(AnyOf, anyOf.valueTypes.map((type) => FullType(type)).toList()))!;
  }

  @override
  SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandate deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateBuilder();
    Object? anyOfDataSrc;
    final targetType = const FullType(AnyOf, [FullType(String), FullType(Mandate), ]);
    anyOfDataSrc = serialized;
    result.anyOf = serializers.deserialize(anyOfDataSrc, specifiedType: targetType) as AnyOf;
    return result.build();
  }
}

class SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum extends EnumClass {

  /// String representing the object's type. Objects of the same type share the same value.
  @BuiltValueEnumConst(wireName: r'mandate')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum mandate = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum_mandate;

  static Serializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum> get serializer => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnumSerializer;

  const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum._(String name): super(name);

  static BuiltSet<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum> get values => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnumValues;
  static SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnum valueOf(String name) => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateObjectEnumValueOf(name);
}

class SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum extends EnumClass {

  /// The mandate status indicates whether or not you can use it to initiate a payment.
  @BuiltValueEnumConst(wireName: r'active')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum active = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum_active;
  /// The mandate status indicates whether or not you can use it to initiate a payment.
  @BuiltValueEnumConst(wireName: r'inactive')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum inactive = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum_inactive;
  /// The mandate status indicates whether or not you can use it to initiate a payment.
  @BuiltValueEnumConst(wireName: r'pending')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum pending = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum_pending;

  static Serializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum> get serializer => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnumSerializer;

  const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum._(String name): super(name);

  static BuiltSet<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum> get values => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnumValues;
  static SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnum valueOf(String name) => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateStatusEnumValueOf(name);
}

class SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum extends EnumClass {

  /// The type of the mandate.
  @BuiltValueEnumConst(wireName: r'multi_use')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum multiUse = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum_multiUse;
  /// The type of the mandate.
  @BuiltValueEnumConst(wireName: r'single_use')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum singleUse = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum_singleUse;

  static Serializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum> get serializer => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnumSerializer;

  const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum._(String name): super(name);

  static BuiltSet<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum> get values => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnumValues;
  static SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnum valueOf(String name) => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitMandateTypeEnumValueOf(name);
}

