//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:stripe_dart_sdk/src/model/payment_method_nz_bank_account.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_card.dart';
import 'package:stripe_dart_sdk/src/model/confirmation_tokens_resource_payment_method_preview_customer.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_ideal.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_us_bank_account.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_link.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_klarna.dart';
import 'dart:core';
import 'package:stripe_dart_sdk/src/model/payment_method_kr_card.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_au_becs_debit.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_card_present.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_sofort.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_fpx.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_interac_present.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_bacs_debit.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_naver_pay.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_p24.dart';
import 'package:stripe_dart_sdk/src/model/payment_method.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_eps.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_acss_debit.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_sepa_debit.dart';
import 'package:built_collection/built_collection.dart';
import 'package:stripe_dart_sdk/src/model/radar_radar_options.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_cashapp.dart';
import 'package:stripe_dart_sdk/src/model/billing_details.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_boleto.dart';
import 'package:built_value/json_object.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_paypal.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:one_of/any_of.dart';

part 'setup_attempt_payment_method_details_bancontact_generated_sepa_debit.g.dart';

/// The ID of the SEPA Direct Debit PaymentMethod which was generated by this SetupAttempt.
///
/// Properties:
/// * [acssDebit] 
/// * [affirm] - 
/// * [afterpayClearpay] - 
/// * [alipay] - 
/// * [allowRedisplay] - This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
/// * [alma] - 
/// * [amazonPay] - 
/// * [auBecsDebit] 
/// * [bacsDebit] 
/// * [bancontact] - 
/// * [billie] - 
/// * [billingDetails] 
/// * [blik] - 
/// * [boleto] 
/// * [card] 
/// * [cardPresent] 
/// * [cashapp] 
/// * [created] - Time at which the object was created. Measured in seconds since the Unix epoch.
/// * [crypto] - 
/// * [customer] 
/// * [customerBalance] - 
/// * [eps] 
/// * [fpx] 
/// * [giropay] - 
/// * [grabpay] - 
/// * [id] - Unique identifier for the object.
/// * [ideal] 
/// * [interacPresent] 
/// * [kakaoPay] - 
/// * [klarna] 
/// * [konbini] - 
/// * [krCard] 
/// * [link] 
/// * [livemode] - Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
/// * [metadata] - Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
/// * [mobilepay] - 
/// * [multibanco] - 
/// * [naverPay] 
/// * [nzBankAccount] 
/// * [object] - String representing the object's type. Objects of the same type share the same value.
/// * [oxxo] - 
/// * [p24] 
/// * [payByBank] - 
/// * [payco] - 
/// * [paynow] - 
/// * [paypal] 
/// * [pix] - 
/// * [promptpay] - 
/// * [radarOptions] 
/// * [revolutPay] - 
/// * [samsungPay] - 
/// * [satispay] - 
/// * [sepaDebit] 
/// * [sofort] 
/// * [swish] - 
/// * [twint] - 
/// * [type] - The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
/// * [usBankAccount] 
/// * [wechatPay] - 
/// * [zip] - 
@BuiltValue()
abstract class SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit implements Built<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit, SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitBuilder> {
  /// Any Of [PaymentMethod], [String]
  AnyOf get anyOf;

  SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit._();

  factory SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit([void updates(SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitBuilder b)]) = _$SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit> get serializer => _$SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitSerializer();
}

class _$SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitSerializer implements PrimitiveSerializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit> {
  @override
  final Iterable<Type> types = const [SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit, _$SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit];

  @override
  final String wireName = r'SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
  }

  @override
  Object serialize(
    Serializers serializers,
    SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final anyOf = object.anyOf;
    return serializers.serialize(anyOf, specifiedType: FullType(AnyOf, anyOf.valueTypes.map((type) => FullType(type)).toList()))!;
  }

  @override
  SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebit deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitBuilder();
    Object? anyOfDataSrc;
    final targetType = const FullType(AnyOf, [FullType(String), FullType(PaymentMethod), ]);
    anyOfDataSrc = serialized;
    result.anyOf = serializers.deserialize(anyOfDataSrc, specifiedType: targetType) as AnyOf;
    return result.build();
  }
}

class SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum extends EnumClass {

  /// This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
  @BuiltValueEnumConst(wireName: r'always')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum always = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum_always;
  /// This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
  @BuiltValueEnumConst(wireName: r'limited')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum limited = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum_limited;
  /// This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
  @BuiltValueEnumConst(wireName: r'unspecified')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum unspecified = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum_unspecified;

  static Serializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum> get serializer => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnumSerializer;

  const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum._(String name): super(name);

  static BuiltSet<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum> get values => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnumValues;
  static SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnum valueOf(String name) => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitAllowRedisplayEnumValueOf(name);
}

class SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum extends EnumClass {

  /// String representing the object's type. Objects of the same type share the same value.
  @BuiltValueEnumConst(wireName: r'payment_method')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum paymentMethod = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum_paymentMethod;

  static Serializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum> get serializer => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnumSerializer;

  const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum._(String name): super(name);

  static BuiltSet<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum> get values => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnumValues;
  static SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnum valueOf(String name) => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitObjectEnumValueOf(name);
}

class SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum extends EnumClass {

  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'acss_debit')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum acssDebit = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_acssDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'affirm')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum affirm = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_affirm;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'afterpay_clearpay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum afterpayClearpay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_afterpayClearpay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'alipay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum alipay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_alipay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'alma')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum alma = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_alma;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'amazon_pay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum amazonPay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_amazonPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'au_becs_debit')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum auBecsDebit = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_auBecsDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'bacs_debit')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum bacsDebit = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_bacsDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'bancontact')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum bancontact = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_bancontact;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'billie')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum billie = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_billie;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'blik')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum blik = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_blik;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'boleto')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum boleto = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_boleto;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'card')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum card = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_card;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'card_present')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum cardPresent = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_cardPresent;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'cashapp')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum cashapp = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_cashapp;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'crypto')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum crypto = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_crypto;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'customer_balance')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum customerBalance = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_customerBalance;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'eps')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum eps = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_eps;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'fpx')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum fpx = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_fpx;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'giropay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum giropay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_giropay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'grabpay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum grabpay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_grabpay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'ideal')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum ideal = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_ideal;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'interac_present')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum interacPresent = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_interacPresent;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'kakao_pay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum kakaoPay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_kakaoPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'klarna')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum klarna = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_klarna;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'konbini')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum konbini = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_konbini;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'kr_card')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum krCard = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_krCard;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'link')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum link = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_link;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'mobilepay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum mobilepay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_mobilepay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'multibanco')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum multibanco = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_multibanco;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'naver_pay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum naverPay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_naverPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'nz_bank_account')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum nzBankAccount = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_nzBankAccount;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'oxxo')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum oxxo = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_oxxo;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'p24')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum p24 = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_p24;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'pay_by_bank')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum payByBank = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_payByBank;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'payco')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum payco = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_payco;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'paynow')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum paynow = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_paynow;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'paypal')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum paypal = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_paypal;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'pix')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum pix = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_pix;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'promptpay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum promptpay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_promptpay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'revolut_pay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum revolutPay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_revolutPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'samsung_pay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum samsungPay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_samsungPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'satispay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum satispay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_satispay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'sepa_debit')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum sepaDebit = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_sepaDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'sofort')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum sofort = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_sofort;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'swish')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum swish = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_swish;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'twint')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum twint = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_twint;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'us_bank_account')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum usBankAccount = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_usBankAccount;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'wechat_pay')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum wechatPay = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_wechatPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'zip')
  static const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum zip = _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum_zip;

  static Serializer<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum> get serializer => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnumSerializer;

  const SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum._(String name): super(name);

  static BuiltSet<SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum> get values => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnumValues;
  static SetupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnum valueOf(String name) => _$setupAttemptPaymentMethodDetailsBancontactGeneratedSepaDebitTypeEnumValueOf(name);
}

