//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:stripe_dart_sdk/src/model/payment_method_nz_bank_account.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_card.dart';
import 'package:stripe_dart_sdk/src/model/confirmation_tokens_resource_payment_method_preview_customer.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_ideal.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_us_bank_account.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_link.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_klarna.dart';
import 'dart:core';
import 'package:stripe_dart_sdk/src/model/payment_method_kr_card.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_au_becs_debit.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_card_present.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_sofort.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_fpx.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_interac_present.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_bacs_debit.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_naver_pay.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_p24.dart';
import 'package:stripe_dart_sdk/src/model/payment_method.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_eps.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_acss_debit.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_sepa_debit.dart';
import 'package:built_collection/built_collection.dart';
import 'package:stripe_dart_sdk/src/model/radar_radar_options.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_cashapp.dart';
import 'package:stripe_dart_sdk/src/model/billing_details.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_boleto.dart';
import 'package:built_value/json_object.dart';
import 'package:stripe_dart_sdk/src/model/payment_method_paypal.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';
import 'package:one_of/any_of.dart';

part 'setup_attempt_payment_method_details_card_present_generated_card.g.dart';

/// The ID of the Card PaymentMethod which was generated by this SetupAttempt.
///
/// Properties:
/// * [acssDebit] 
/// * [affirm] - 
/// * [afterpayClearpay] - 
/// * [alipay] - 
/// * [allowRedisplay] - This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
/// * [alma] - 
/// * [amazonPay] - 
/// * [auBecsDebit] 
/// * [bacsDebit] 
/// * [bancontact] - 
/// * [billie] - 
/// * [billingDetails] 
/// * [blik] - 
/// * [boleto] 
/// * [card] 
/// * [cardPresent] 
/// * [cashapp] 
/// * [created] - Time at which the object was created. Measured in seconds since the Unix epoch.
/// * [crypto] - 
/// * [customer] 
/// * [customerBalance] - 
/// * [eps] 
/// * [fpx] 
/// * [giropay] - 
/// * [grabpay] - 
/// * [id] - Unique identifier for the object.
/// * [ideal] 
/// * [interacPresent] 
/// * [kakaoPay] - 
/// * [klarna] 
/// * [konbini] - 
/// * [krCard] 
/// * [link] 
/// * [livemode] - Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
/// * [metadata] - Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.
/// * [mobilepay] - 
/// * [multibanco] - 
/// * [naverPay] 
/// * [nzBankAccount] 
/// * [object] - String representing the object's type. Objects of the same type share the same value.
/// * [oxxo] - 
/// * [p24] 
/// * [payByBank] - 
/// * [payco] - 
/// * [paynow] - 
/// * [paypal] 
/// * [pix] - 
/// * [promptpay] - 
/// * [radarOptions] 
/// * [revolutPay] - 
/// * [samsungPay] - 
/// * [satispay] - 
/// * [sepaDebit] 
/// * [sofort] 
/// * [swish] - 
/// * [twint] - 
/// * [type] - The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
/// * [usBankAccount] 
/// * [wechatPay] - 
/// * [zip] - 
@BuiltValue()
abstract class SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard implements Built<SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard, SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardBuilder> {
  /// Any Of [PaymentMethod], [String]
  AnyOf get anyOf;

  SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard._();

  factory SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard([void updates(SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardBuilder b)]) = _$SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard> get serializer => _$SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardSerializer();
}

class _$SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardSerializer implements PrimitiveSerializer<SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard> {
  @override
  final Iterable<Type> types = const [SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard, _$SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard];

  @override
  final String wireName = r'SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
  }

  @override
  Object serialize(
    Serializers serializers,
    SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final anyOf = object.anyOf;
    return serializers.serialize(anyOf, specifiedType: FullType(AnyOf, anyOf.valueTypes.map((type) => FullType(type)).toList()))!;
  }

  @override
  SetupAttemptPaymentMethodDetailsCardPresentGeneratedCard deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardBuilder();
    Object? anyOfDataSrc;
    final targetType = const FullType(AnyOf, [FullType(String), FullType(PaymentMethod), ]);
    anyOfDataSrc = serialized;
    result.anyOf = serializers.deserialize(anyOfDataSrc, specifiedType: targetType) as AnyOf;
    return result.build();
  }
}

class SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum extends EnumClass {

  /// This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
  @BuiltValueEnumConst(wireName: r'always')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum always = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum_always;
  /// This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
  @BuiltValueEnumConst(wireName: r'limited')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum limited = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum_limited;
  /// This field indicates whether this payment method can be shown again to its customer in a checkout flow. Stripe products such as Checkout and Elements use this field to determine whether a payment method can be shown as a saved payment method in a checkout flow. The field defaults to “unspecified”.
  @BuiltValueEnumConst(wireName: r'unspecified')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum unspecified = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum_unspecified;

  static Serializer<SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum> get serializer => _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnumSerializer;

  const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum._(String name): super(name);

  static BuiltSet<SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum> get values => _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnumValues;
  static SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnum valueOf(String name) => _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardAllowRedisplayEnumValueOf(name);
}

class SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnum extends EnumClass {

  /// String representing the object's type. Objects of the same type share the same value.
  @BuiltValueEnumConst(wireName: r'payment_method')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnum paymentMethod = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnum_paymentMethod;

  static Serializer<SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnum> get serializer => _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnumSerializer;

  const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnum._(String name): super(name);

  static BuiltSet<SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnum> get values => _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnumValues;
  static SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnum valueOf(String name) => _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardObjectEnumValueOf(name);
}

class SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum extends EnumClass {

  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'acss_debit')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum acssDebit = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_acssDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'affirm')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum affirm = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_affirm;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'afterpay_clearpay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum afterpayClearpay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_afterpayClearpay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'alipay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum alipay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_alipay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'alma')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum alma = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_alma;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'amazon_pay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum amazonPay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_amazonPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'au_becs_debit')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum auBecsDebit = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_auBecsDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'bacs_debit')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum bacsDebit = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_bacsDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'bancontact')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum bancontact = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_bancontact;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'billie')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum billie = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_billie;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'blik')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum blik = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_blik;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'boleto')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum boleto = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_boleto;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'card')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum card = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_card;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'card_present')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum cardPresent = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_cardPresent;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'cashapp')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum cashapp = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_cashapp;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'crypto')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum crypto = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_crypto;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'customer_balance')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum customerBalance = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_customerBalance;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'eps')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum eps = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_eps;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'fpx')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum fpx = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_fpx;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'giropay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum giropay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_giropay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'grabpay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum grabpay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_grabpay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'ideal')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum ideal = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_ideal;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'interac_present')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum interacPresent = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_interacPresent;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'kakao_pay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum kakaoPay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_kakaoPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'klarna')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum klarna = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_klarna;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'konbini')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum konbini = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_konbini;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'kr_card')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum krCard = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_krCard;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'link')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum link = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_link;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'mobilepay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum mobilepay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_mobilepay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'multibanco')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum multibanco = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_multibanco;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'naver_pay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum naverPay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_naverPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'nz_bank_account')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum nzBankAccount = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_nzBankAccount;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'oxxo')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum oxxo = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_oxxo;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'p24')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum p24 = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_p24;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'pay_by_bank')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum payByBank = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_payByBank;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'payco')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum payco = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_payco;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'paynow')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum paynow = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_paynow;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'paypal')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum paypal = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_paypal;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'pix')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum pix = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_pix;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'promptpay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum promptpay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_promptpay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'revolut_pay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum revolutPay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_revolutPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'samsung_pay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum samsungPay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_samsungPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'satispay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum satispay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_satispay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'sepa_debit')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum sepaDebit = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_sepaDebit;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'sofort')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum sofort = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_sofort;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'swish')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum swish = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_swish;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'twint')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum twint = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_twint;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'us_bank_account')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum usBankAccount = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_usBankAccount;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'wechat_pay')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum wechatPay = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_wechatPay;
  /// The type of the PaymentMethod. An additional hash is included on the PaymentMethod with a name matching this value. It contains additional information specific to the PaymentMethod type.
  @BuiltValueEnumConst(wireName: r'zip')
  static const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum zip = _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum_zip;

  static Serializer<SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum> get serializer => _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnumSerializer;

  const SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum._(String name): super(name);

  static BuiltSet<SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum> get values => _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnumValues;
  static SetupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnum valueOf(String name) => _$setupAttemptPaymentMethodDetailsCardPresentGeneratedCardTypeEnumValueOf(name);
}

