//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'setup_intent_payment_method_options_paypal.g.dart';

/// 
///
/// Properties:
/// * [billingAgreementId] - The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
@BuiltValue()
abstract class SetupIntentPaymentMethodOptionsPaypal implements Built<SetupIntentPaymentMethodOptionsPaypal, SetupIntentPaymentMethodOptionsPaypalBuilder> {
  /// The PayPal Billing Agreement ID (BAID). This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
  @BuiltValueField(wireName: r'billing_agreement_id')
  String? get billingAgreementId;

  SetupIntentPaymentMethodOptionsPaypal._();

  factory SetupIntentPaymentMethodOptionsPaypal([void updates(SetupIntentPaymentMethodOptionsPaypalBuilder b)]) = _$SetupIntentPaymentMethodOptionsPaypal;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(SetupIntentPaymentMethodOptionsPaypalBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<SetupIntentPaymentMethodOptionsPaypal> get serializer => _$SetupIntentPaymentMethodOptionsPaypalSerializer();
}

class _$SetupIntentPaymentMethodOptionsPaypalSerializer implements PrimitiveSerializer<SetupIntentPaymentMethodOptionsPaypal> {
  @override
  final Iterable<Type> types = const [SetupIntentPaymentMethodOptionsPaypal, _$SetupIntentPaymentMethodOptionsPaypal];

  @override
  final String wireName = r'SetupIntentPaymentMethodOptionsPaypal';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    SetupIntentPaymentMethodOptionsPaypal object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    if (object.billingAgreementId != null) {
      yield r'billing_agreement_id';
      yield serializers.serialize(
        object.billingAgreementId,
        specifiedType: const FullType.nullable(String),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    SetupIntentPaymentMethodOptionsPaypal object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required SetupIntentPaymentMethodOptionsPaypalBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'billing_agreement_id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.billingAgreementId = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  SetupIntentPaymentMethodOptionsPaypal deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = SetupIntentPaymentMethodOptionsPaypalBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

